name: Elixir CI

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      env:
        REDIS_HOST: redis
        REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
      run: mix test
